-- Schema SALAM
CREATE SCHEMA IF NOT EXISTS SALAM AUTHORIZATION postgres;

SET search_path TO SALAM;

-- Tabel Mahasiswa engan Constraint
CREATE TABLE SALAM.mahasiswas (
    id SERIAL PRIMARY KEY,
    nim VARCHAR(10) UNIQUE NOT NULL,
    nama VARCHAR(100) NOT NULL,
    umur INT CHECK (umur >= 17),
    jurusan VARCHAR(100) NOT NULL
);

-- Tambah Data 
INSERT INTO SALAM.mahasiswas (nim, nama, umur, jurusan)
VALUES
('1237050063', 'Rizkia Nuari', 20, 'Teknik Informatika');

-- Buat User Baru dan Atur Hak Akses
CREATE ROLE backend_dev LOGIN PASSWORD 'backend063';
GRANT CONNECT ON DATABASE salamdb TO backend_dev;
GRANT USAGE ON SCHEMA SALAM TO backend_dev;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA SALAM TO backend_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM GRANT ALL ON TABLES TO backend_dev;

CREATE ROLE bi_dev LOGIN PASSWORD 'bidev063';
GRANT CONNECT ON DATABASE salamdb TO bi_dev;
GRANT USAGE ON SCHEMA SALAM TO bi_dev;
GRANT SELECT ON ALL TABLES IN SCHEMA SALAM TO bi_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM GRANT SELECT ON TABLES TO bi_dev;

CREATE ROLE data_engineer LOGIN PASSWORD 'engineer063';
GRANT CONNECT ON DATABASE salamdb TO data_engineer;
GRANT USAGE, CREATE ON SCHEMA SALAM TO data_engineer;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA SALAM TO data_engineer;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM GRANT ALL ON TABLES TO data_engineer;
